# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run Fastlane

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  # Ensure this matches the required version
    - name: Install Bundler
      run: gem install bundler -v 2.6.3
    - name: Install dependencies
      run: bundle install
    - name: Skip Swift Macros
      run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
    - uses: maierj/fastlane-action@v3.1.0
      with:
        lane: 'tests'
